apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  labels:
    app: node-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-todo-app
  template:
    metadata:
      labels:
        app: node-todo-app
    spec:
      containers:
      - name: node-todo-app
        image: 029956535309.dkr.ecr.ap-south-1.amazonaws.com/todo-app-repo:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: node-todo-app
spec:
  type: LoadBalancer
  selector:
    app: node-todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

